# Generated by Django 3.2.5 on 2021-07-28 11:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.UUID('45749ae9-f9fb-494e-9ae5-76fad9ca459a'), verbose_name='Slug')),
                ('longitude', models.CharField(blank=True, max_length=150, null=True, verbose_name='Longitude')),
                ('latitude', models.CharField(blank=True, max_length=150, null=True, verbose_name='Longitude')),
                ('aq', models.CharField(max_length=50, verbose_name='Air Quality (%)')),
                ('co', models.CharField(max_length=50, verbose_name='Carbon monoxide (ppm)')),
                ('h', models.CharField(max_length=50, verbose_name='Hydrogene')),
                ('lpg', models.CharField(max_length=50, verbose_name='LPG (ppm)')),
                ('t', models.CharField(max_length=50, verbose_name='Temperature (°)')),
                ('smoke', models.CharField(max_length=50, verbose_name='Smoke (ppm)')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
    ]
