# Generated by Django 3.2.5 on 2021-07-28 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0002_auto_20210728_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airquality',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3677b1f5-bf46-4a37-a1e2-ec84173df7ec'), verbose_name='Slug'),
        ),
    ]
