# Generated by Django 3.2.5 on 2021-08-03 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0004_auto_20210728_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airquality',
            name='slug',
            field=models.SlugField(default=uuid.UUID('087e89f0-d048-4d2c-b2d5-0ad740746dd3'), verbose_name='Slug'),
        ),
    ]
