# Generated by Django 3.2.5 on 2021-08-12 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0012_alter_airquality_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airquality',
            name='slug',
            field=models.SlugField(default=uuid.UUID('34ddb014-e3d9-49f4-97c8-de7d68da503f'), verbose_name='Slug'),
        ),
    ]
