# Generated by Django 3.2.5 on 2021-08-12 16:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0014_alter_airquality_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airquality',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e2420531-3f9c-4cab-9d08-d7aab4998b6a'), verbose_name='Slug'),
        ),
    ]
