# Generated by Django 3.2.6 on 2021-08-13 14:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0015_alter_airquality_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airquality',
            name='slug',
            field=models.SlugField(default=uuid.UUID('65d0ba10-c1a2-4c96-8088-5ad53f49da81'), verbose_name='Slug'),
        ),
    ]
