# Generated by Django 3.2.5 on 2021-08-12 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(default=uuid.UUID('fcdd91e0-68c9-4b22-9f08-f9f75966f4eb'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3d88b458-8bca-4540-a447-000c665a0b05'), verbose_name='Slug'),
        ),
    ]
