# Generated by Django 3.2.5 on 2021-08-12 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_auto_20210812_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(default=uuid.UUID('195533ca-5684-419c-a7fb-cb3db0b8036b'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7181afec-5559-4207-90b4-b7b5b4342b99'), verbose_name='Slug'),
        ),
    ]
