# Generated by Django 3.2.5 on 2021-08-12 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_auto_20210812_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(default=uuid.UUID('4593dd7f-4ee4-4c46-82db-6ab6ade820cc'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='slug',
            field=models.SlugField(default=uuid.UUID('8aa8789e-16ca-4907-b45c-fe1eb221ed8e'), verbose_name='Slug'),
        ),
    ]
