# Generated by Django 3.2.5 on 2021-08-12 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_auto_20210812_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(default=uuid.UUID('991c1eeb-4812-4df2-8580-ef01b32c5edb'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3439f119-412c-45eb-b58a-473ed15a704d'), verbose_name='Slug'),
        ),
    ]
