# Generated by Django 3.2.5 on 2021-08-12 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_auto_20210812_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='cin',
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(default=uuid.UUID('31cf7312-1237-4271-9e1e-8036abfeb1a5'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='slug',
            field=models.SlugField(default=uuid.UUID('adb5e9cd-611b-4bcc-9293-267d7eaf3eaf'), verbose_name='Slug'),
        ),
    ]
