# Generated by Django 3.2.6 on 2021-08-13 14:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0008_auto_20210812_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f255e5be-ae30-4f51-b1c5-d11e848c44af'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='slug',
            field=models.SlugField(default=uuid.UUID('116547c6-eecf-483b-a4fd-4e4a76c9f00c'), verbose_name='Slug'),
        ),
    ]
